#162: remove deleted rule BeanMembersShouldSerialize
dgroup/arch4u-pmd pull request #163
Opened 2023-07-26 09:22 UTC by emouty

Fix #162

2023-07-26 13:12 UTC, dgroup requested changes

2023-07-26 14:24 UTC, emouty commented on readme.md
> +    <plugins>
Hello, 
yes, my bad I had auto formatting enabled :sweat_smile:

2023-07-28 19:52 UTC, merged

2023-07-28 19:53 UTC, dgroup commented
@rultor release tag=`0.2.6`

2023-07-28 19:55 UTC, rultor commented
> @rultor release tag=`0.2.6`

@dgroup OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/33665-1656241718)

2023-07-28 19:59 UTC, rultor commented
> @rultor release tag=`0.2.6`

@dgroup Done! FYI, the full log is [here](https://www.rultor.com/t/33665-1656241718) (took me 3min)